### ISSUE TITLE
TypeError: (intermediate value).readToken_question is not a function

### ISSUE THREAD

**Issue by magiblot** [acornjs/acorn-logical-assignment#2]
Hi,

After updating to 0.1.1 I get the following exception:
```js
TypeError: (intermediate value).readToken_question is not a function
    at Object.readToken_question (node_modules/acorn-logical-assignment/index.js:32:20)
    at Object.getTokenFromCode (node_modules/acorn-logical-assignment/index.js:20:32)
    at Object.pp$9.readToken (node_modules/acorn/dist/acorn.js:4288:17)
    at Object.readToken (node_modules/acorn-jsx/index.js:469:20)
    at Object.pp$9.nextToken (node_modules/acorn/dist/acorn.js:4279:17)
    at Object.pp$9.next (node_modules/acorn/dist/acorn.js:4236:10)
    at Object.pp.eat (node_modules/acorn/dist/acorn.js:619:12)
    at Object.pp$3.parseExprList (node_modules/acorn/dist/acorn.js:2714:18)
    at Object.pp$3.parseSubscript (node_modules/acorn/dist/acorn.js:2124:27)
    at Object.parseSubscript (node_modules/acorn-private-class-elements/index.js:122:37)
    at Object.pp$3.parseSubscripts (node_modules/acorn/dist/acorn.js:2104:26)
    at Object.pp$3.parseExprSubscripts (node_modules/acorn/dist/acorn.js:2092:23)
    at Object.pp$3.parseMaybeUnary (node_modules/acorn/dist/acorn.js:2066:19)
    at Object.parseMaybeUnary (node_modules/acorn-private-class-elements/index.js:154:29)
    at Object.pp$3.parseExprOps (node_modules/acorn/dist/acorn.js:2010:21)
    at Object.pp$3.parseMaybeConditional (node_modules/acorn/dist/acorn.js:1993:21)
    at Object.pp$3.parseMaybeAssign (node_modules/acorn/dist/acorn.js:1968:21)
    at Object.pp$1.parseVar (node_modules/acorn/dist/acorn.js:1228:26)
    at Object.pp$1.parseVarStatement (node_modules/acorn/dist/acorn.js:1092:10)
    at Object.pp$1.parseStatement (node_modules/acorn/dist/acorn.js:842:19)
    at Object.parseStatement (node_modules/acorn-dynamic-import/lib/index.js:63:118)
    at Object.parseStatement (node_modules/acorn-import-meta/index.js:39:22)
    at Object.pp$1.parseTopLevel (node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse (node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (node_modules/acorn/dist/acorn.js:576:37)
  code: 'var f = () => true;\nconst v = f() ? 0 : 4;'
}
```
Downgrading to 0.1.0 solves the issue.

**Comment by Rovniy** [comment]
Me too

**Comment by adrianheine** [comment]
Fixed with c50842e89be8c7f1c1cb69402fa76631d2fa378b and released as 0.1.3.

**Comment by magiblot** [comment]
Thanks!
